{
 "title": "ECS Overview",
 "tags": [
  "ECS",
  "Overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Job", "label": "Exporter Service Name", "query": "label_values(up,  job)" }
  ]
 },
 "panels": [
  { "title": "Alerts ", "type": "gauge" },
  {
   "title": "P95 CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "quantile(0.95, aliyun_acs_ecs_dashboard_CPUUtilization)",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "P95 Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "quantile(0.95, aliyun_acs_ecs_dashboard_load_5m)",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "P95 Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "quantile(0.95, aliyun_acs_ecs_dashboard_memory_usedutilization)",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "percentage_cpu_percent_average{job=\"$Job\"}"
    },
    {
     "expr": "aliyun_acs_ecs_dashboard_CPUUtilization{job=\"$Job\"}"
    }
   ]
  },
  {
   "title": "Average CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aliyun_acs_ecs_dashboard_CPUUtilization{job=\"$Job\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_CPUUtilization{job=\"$Job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_memory_usedutilization[$interval]) > 95) * on (instanceId) group_left(VpcAttributes,HostName,InnerIpAddress) \nlabel_replace(aliyun_meta_ecs_info,\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_InternetIn{job=\"$Job\"})",
     "legendFormat": "InBound Internet Usage"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_InternetOut{job=\"$Job\"})"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_diskusage_utilization[$interval]) > 90) * on (instanceId) group_left(VpcAttributes,HostName,InnerIpAddress) \nlabel_replace(aliyun_meta_ecs_info,\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")"
    }
   ]
  },
  {
   "title": "Too Many Connections",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_net_tcpconnection{state=\"TCP_TOTAL\"}[10m]) > 1000) * on (instanceId) group_left(VpcAttributes,HostName,InnerIpAddress) \nlabel_replace(aliyun_meta_ecs_info,\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")"
    }
   ]
  },
  {
   "title": "Abnormal Network IO",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_InternetOut[10m]) > 10 * 1024 * 1024) * on (instanceId) group_left(VpcAttributes,HostName,InnerIpAddress) \nlabel_replace(aliyun_meta_ecs_info,\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")"
    }
   ]
  }
 ]
}